export const ROLES = {
  TRAVELER: 'TRAVELER',
  TOUR_AGENT: 'TOUR_AGENT',
  AGENCY_MANAGER: 'AGENCY_MANAGER',
};

// Single source of truth for who can do what.
// Traveler = browse + apply. Agent = operate (create/update, no delete/publish).
// Manager = full control everywhere.
const CAN = {
  CREATE_PACKAGE: [ROLES.AGENCY_MANAGER],
  EDIT_PACKAGE: [ROLES.AGENCY_MANAGER],
  DELETE_PACKAGE: [ROLES.AGENCY_MANAGER],
  APPLY_PACKAGE: [ROLES.TRAVELER],

  CREATE_ITINERARY: [ROLES.AGENCY_MANAGER, ROLES.TOUR_AGENT],
  EDIT_ITINERARY: [ROLES.AGENCY_MANAGER, ROLES.TOUR_AGENT],
  DELETE_ITINERARY: [ROLES.AGENCY_MANAGER],
  CONFIRM_ITINERARY: [ROLES.AGENCY_MANAGER, ROLES.TOUR_AGENT],

  CREATE_ACTIVITY: [ROLES.AGENCY_MANAGER, ROLES.TOUR_AGENT],
  DELETE_ACTIVITY: [ROLES.AGENCY_MANAGER],

  MANAGE_BOOKINGS: [ROLES.AGENCY_MANAGER, ROLES.TOUR_AGENT],
  CREATE_OWN_BOOKING: [ROLES.TRAVELER],

  MANAGE_ACCOUNTS: [ROLES.AGENCY_MANAGER],
};

export const can = (role, permission) => (CAN[permission] || []).includes(role);